name: trionesdev_antd_mobile
description: "antd ui"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  flutter_svg: ^2.0.17
  collection: ^1.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  assets:
    - assets/images/empty.svg
    - assets/images/default-image.svg
    - assets/images/default-image.png
    - assets/images/error-image.svg
    - assets/images/error-image.png
